[workspace]
# Allow release-plz to update the dependencies of the packages in the workspace
allow_dirty = ["Cargo.toml", "Cargo.lock"]

[[package]]
name = "dd_sketchy"
# Include all commits in changelog
changelog_include = [".*"]
# Generate changelog entries for conventional commits
changelog_update = true
# Tag format for releases
tag_name = "v{{ version }}"
# Release name format
release_name = "v{{ version }}"